
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  jupyter:
    image: jupyter/pyspark-notebook:python-3.11
    ports:
      - "8888:8888"
      - "4050:4050"
    environment:
      JUPYTER_TOKEN: "mysecrettoken"
    volumes:
     - ./dados:/home/jovyan/work/dados
     - ./exemplos:/home/jovyan/work/exemplos
     - ./notebooks:/home/jovyan/work/notebooks
    depends_on:
      - minio

volumes:
  minio_data:
